### ISSUE TITLE
todo operation not working properly

### ISSUE THREAD

**Issue by Dipesh-Budhiraja** [coding-blocks-archives/DwarkaNodejs2017Summer#1]
When the page is loaded and all cache memory is cleared and then refreshed, then while adding the first element to list it doesn't appear on the web page but it is set in loacalStorage. everything works fine from the second element that is added. Please, clear cache memory to check the bug. **File is in class-8 folder**

**Comment by aayusharora** [comment]
Thanks @Dipesh-Budhiraja Can you please check now, just changed the index to 0.
